### ISSUE TITLE
Roadmap for removing Python 2 support

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#2803]
## Phase 1 (v2.8) DONE
Nov. 2017

- [x] Standalone installers for Windows, macOS and generic Linux will ship Python 3.5
- [x]  Linux binary packages will still use Python 2.7
- [x]  Binary wheels for Python 2.7 will be kept
- [x]  Python 2.7 tested by Jenkins and Travis
- [x] VM running Python 2.7

## Phase 2 (v2.9) DONE
Feb. 2018

- [x]  Linux binary packages (RPM and DEB) will run on Python 3.5. An `oq-python35` package, which will provide python3.5 in `/opt/openquake/`, will be released
- [x]  Binary wheels for Python 2.7 will be kept
- [x]  Python 2.7 tested by Travis only
- [x]  VM running Python 2.7

## Phase 3 (v3.0) IN PROGRESS
Apr. 2018

- [x]  VM uses Python 3 as main Python (https://github.com/gem/oq-builders/issues/90)
- [x]  Support for Python 2.7 is removed
- [x]  Python 2.7 wheels are discontinued
- [x]  No more CI on Python 2.7

**Comment by daniviga** [comment]
Phase 1 is implemented in:
- https://github.com/gem/oq-engine/pull/3230
- https://github.com/gem/oq-builders/pull/79
- https://github.com/gem/oq-builders/pull/80
- https://github.com/gem/oq-builders/pull/81

and will land in 2.8.0

**Comment by daniviga** [comment]
Phase 1 completed

**Comment by daniviga** [comment]
Phase 2 for RHEL is impemented in:
- https://github.com/gem/oq-python-dist/pull/3
- https://github.com/gem/oq-libs/pull/25
- https://github.com/gem/oq-engine/pull/3340

**Comment by daniviga** [comment]
Migration of RHEL packages completed. Ubuntu upcoming.

**Comment by daniviga** [comment]
Phase 2 completed with `engine-2.9`

**Comment by daniviga** [comment]
Phase 3 has begun:

- https://github.com/gem/oq-platform-standalone/pull/30
- https://github.com/gem/oq-irmt-qgis/pull/398

**Comment by daniviga** [comment]
> After a long transition period (~two years) in which the engine worked both with Python 2.7 and 3.5, it is now finally time to abandon Python 2.
>The current master has already abandoned compatibility with Python 2 and  the next release of the engine will only support Python 3.5+.
Graeme has updated the Strong Motion Toolkit to work with Python 3, so there should no problem there. >The Risk Model Toolkit has no problem because it does not import the engine. The QGIS plugin has no problem because it uses the Web API and does not import the engine. The notebooks could have problems, please test them.
>
>If you find any issue, please let us know.
>
>             MIchele and Daniele

**Comment by daniviga** [comment]
Master version bumped to 3.0 via https://github.com/gem/oq-engine/commit/82690686503fda8872c0ed09ea6204d5930235d4. Closing.
